export enum typeTask {
  GET_EXCHANGE_RATE = "GET_EXCHANGE_RATE",
  GET_CURRENCIES = "GET_CURRENCIES",
  SET_NEWFROMCURRENCY = "SET_NEWFROMCURRENCY",
  SET_NEWTOCURRENCY = "SET_NEWTOCURRENCY",
  REMOVE_EXCHANGE_RATE = "REMOVE_EXCHANGE_RATE",
  RESET_DATA = "RESET_DATA",
  GET_ERROR = "GET_ERROR",
  SET_LOADING = "SET_LOADING",
  SET_HISTORY = "SET_HISTORY",
  GET_STORAGE = "GET_STORAGE",
  REMOVE_STORAGE = "REMOVE_STORAGE",
}
